branch-defaults:
  default:
    environment: image-proxy-dev
    group_suffix: null
global:
  application_name: image-proxy
  default_platform: Docker 1.9.1
  default_region: us-east-1
  profile: null
  sc: null
